version : "3.9"
services:
    
  rabbitmq:
    container_name : rabbitmq
    image : rabbitmq:3-management-alpine
    ports : 
      - "5672:5672"
      - "15672:15672"
    environment:
        RABBITMQ_DEFAULT_USER : "guets"
        RABBITMQ_DEFAULT_PASS : "guets"
        RABBITMQ_DEFAULT_VHOST : "rabbitmq"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      